[package]
name = "parcel-bench"
version = "0.1.0"
edition = "2021"
workspace = ".."

[dev-dependencies]
criterion = "0.4.0"

[dependencies]
parcel = { git = "https://github.com/ncatelli/parcel", tag = "v2.0.1" }
